"""Framework-independent financial domain primitives."""

from researchforge.domain.finance import (
    absolute_change,
    cash_conversion,
    compare_fact_periods,
    derive_discrete_from_ytd,
    gross_margin,
    gross_profit,
    growth_rate,
    margin_change_pp,
    normalize_to_base_units,
    profit_cash_divergence,
    working_capital_change,
)
from researchforge.domain.models import (
    CalculationResult,
    CalculationStatus,
    ComparabilityResult,
    ComparisonKind,
    DerivationResult,
    FactKind,
    FinancialFact,
    FiscalPeriod,
    MeasurementUnit,
    MetricCode,
    PeriodBasis,
    ReportingPeriod,
    RestatementStatus,
    StatementScope,
)
from researchforge.domain.source_mapping import (
    SOURCE_MAPPING_VERSION,
    SOURCE_METRIC_MAPPINGS,
    MappingTransform,
    SourceMetricMapping,
    StatementCode,
    mapping_for,
)

__all__ = [
    "SOURCE_MAPPING_VERSION",
    "SOURCE_METRIC_MAPPINGS",
    "CalculationResult",
    "CalculationStatus",
    "ComparabilityResult",
    "ComparisonKind",
    "DerivationResult",
    "FactKind",
    "FinancialFact",
    "FiscalPeriod",
    "MappingTransform",
    "MeasurementUnit",
    "MetricCode",
    "PeriodBasis",
    "ReportingPeriod",
    "RestatementStatus",
    "SourceMetricMapping",
    "StatementCode",
    "StatementScope",
    "absolute_change",
    "cash_conversion",
    "compare_fact_periods",
    "derive_discrete_from_ytd",
    "gross_margin",
    "gross_profit",
    "growth_rate",
    "mapping_for",
    "margin_change_pp",
    "normalize_to_base_units",
    "profit_cash_divergence",
    "working_capital_change",
]
